---
env:
  name: DEV

postgres:
  database_url: 'postgres://agflow:agflow@localhost:5432/todo?sslmode=disable'

service:
  port: ':9090'

online_service:
  url: 'http://localhost:9010/objects/'

queue:
  url: 'amqp://guest:guest@localhost:5672//'