package model

import "time"

// Object stores object_ids
type Object struct {
	ObjectIDs []int     `json:"object_ids"`
	ObjectID  int       `json:"id"`
	Online    bool      `json:"online" db:"online"`
	CreatedAt time.Time `db:"created_at"`
}

type AutoGenerated struct {
	ID     int  `json:"id"`
	Online bool `json:"online"`
}
